// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AboutPage: typeof import('./src/components/AboutPage.vue')['default']
    CategoryBox: typeof import('./src/components/home_page/CategoryBox.vue')['default']
    CoursesPage: typeof import('./src/components/course/CoursesPage.vue')['default']
    DynamicAngle: typeof import('./src/components/side_bar/DynamicAngle.vue')['default']
    HomePage: typeof import('./src/components/home_page/HomePage.vue')['default']
    LogInPage: typeof import('./src/components/user/LogInPage.vue')['default']
    NAutoComplete: typeof import('naive-ui')['NAutoComplete']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NDivider: typeof import('naive-ui')['NDivider']
    NestedList: typeof import('./src/components/side_bar/NestedList.vue')['default']
    NewCourse: typeof import('./src/components/course/NewCourse.vue')['default']
    NewReviewPage: typeof import('./src/components/review/NewReviewPage.vue')['default']
    NInput: typeof import('naive-ui')['NInput']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NSelect: typeof import('naive-ui')['NSelect']
    PageBody: typeof import('./src/components/PageBody.vue')['default']
    PageFooter: typeof import('./src/components/PageFooter.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader.vue')['default']
    RecentReviewPage: typeof import('./src/components/review/RecentReviewPage.vue')['default']
    RegisterPage: typeof import('./src/components/user/RegisterPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBox: typeof import('./src/components/search/SearchBox.vue')['default']
    SearchResult: typeof import('./src/components/search/SearchResult.vue')['default']
    SideBar: typeof import('./src/components/side_bar/SideBar.vue')['default']
    SideBarRaw: typeof import('./src/components/side_bar/SideBarRaw.vue')['default']
    SingleCoursePage: typeof import('./src/components/course/SingleCoursePage.vue')['default']
    UserProfile: typeof import('./src/components/user/UserProfile.vue')['default']
  }
}
