// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AboutPage: typeof import('./src/components/AboutPage.vue')['default']
    CoursesPage: typeof import('./src/components/CoursesPage.vue')['default']
    HomePage: typeof import('./src/components/HomePage.vue')['default']
    LogInPage: typeof import('./src/components/LogInPage.vue')['default']
    LogInSection: typeof import('./src/components/LogInSection.vue')['default']
    NAutoComplete: typeof import('naive-ui')['NAutoComplete']
    NButton: typeof import('naive-ui')['NButton']
    NewCourse: typeof import('./src/components/NewCourse.vue')['default']
    NewReviewPage: typeof import('./src/components/NewReviewPage.vue')['default']
    NInput: typeof import('naive-ui')['NInput']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NSelect: typeof import('naive-ui')['NSelect']
    PageBody: typeof import('./src/components/PageBody.vue')['default']
    PageFooter: typeof import('./src/components/PageFooter.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader.vue')['default']
    RecentReviewPage: typeof import('./src/components/RecentReviewPage.vue')['default']
    RegisterSection: typeof import('./src/components/RegisterSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBox: typeof import('./src/components/SearchBox.vue')['default']
    SearchResult: typeof import('./src/components/SearchResult.vue')['default']
    SingleCoursePage: typeof import('./src/components/SingleCoursePage.vue')['default']
    UserProfile: typeof import('./src/components/UserProfile.vue')['default']
  }
}
