// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AboutPage: typeof import('./src/components/AboutPage.vue')['default']
    AllCourses: typeof import('./src/components/course/AllCourses.vue')['default']
    CategoryBox: typeof import('./src/components/home_page/CategoryBox.vue')['default']
    CourseMultipleTeachers: typeof import('./src/components/course/CourseMultipleTeachers.vue')['default']
    DynamicAngle: typeof import('./src/components/side_bar/DynamicAngle.vue')['default']
    HomePage: typeof import('./src/components/home_page/HomePage.vue')['default']
    LogInPage: typeof import('./src/components/user/LogInPage.vue')['default']
    MyReviews: typeof import('./src/components/user/MyReviews.vue')['default']
    MySubmissions: typeof import('./src/components/user/MySubmissions.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NDivider: typeof import('naive-ui')['NDivider']
    NestedList: typeof import('./src/components/side_bar/NestedList.vue')['default']
    NewCourse: typeof import('./src/components/course/NewCourse.vue')['default']
    NewReview: typeof import('./src/components/review/NewReview.vue')['default']
    NInput: typeof import('naive-ui')['NInput']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NSelect: typeof import('naive-ui')['NSelect']
    PageBody: typeof import('./src/components/PageBody.vue')['default']
    PageFooter: typeof import('./src/components/PageFooter.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader.vue')['default']
    RecentReview: typeof import('./src/components/review/RecentReview.vue')['default']
    RegisterPage: typeof import('./src/components/user/RegisterPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchResult: typeof import('./src/components/search/SearchResult.vue')['default']
    SideBar: typeof import('./src/components/side_bar/SideBar.vue')['default']
    SideBarRaw: typeof import('./src/components/side_bar/SideBarRaw.vue')['default']
  }
}
